Better image(s) field + safeguard for github triggered builds
Philmod/google-container-slack pull request #26
Opened 2019-06-01 17:09 UTC by naseemkullah

Hello,

This PR provideds a better image(s) field. That's to say for builds with >1 images the field has name `Images` with 1 value of newline delimited images rather than `Image` and a value per image. 

Before:
```
Image
gcr.io/my-project/my-image-1
Image
gcr.io/my-project/my-image-2
```

After:
```
Images
gcr.io/my-project/my-image-1
gcr.io/my-project/my-image-2
```

Secondly it adds a safeguard for github app triggered builds that do not contain a `build.source.repoSource` object.

Before:
`Error: TypeError: Cannot read property 'repoName' of undefined`
After:
```
Build `1eo8ujfdnbb-83d0-4sjc-8ejd9-329fjfn203` started
Build logs
Status
WORKING
Google Cloud BuildToday at 1:01 PM
```

Finally I've also taken the liberty to update packages.

2019-06-01 18:19 UTC, Philmod requested changes

2019-06-01 18:19 UTC, Philmod commented on index.js
> +  const { repoSource } = build.source || null;
Why this variable name change?

2019-06-01 18:19 UTC, Philmod commented on index.js
> +  if (images.length === 1) {
```
{
  title: 'Image' + ((images.length > 1) ? 's' : ''),
  value: images.join('\n'),
}
```

2019-06-01 18:19 UTC, Philmod commented on test.js
> +    // const build = lib.eventToBuild(base64Build);
Forgot to delete?

2019-06-01 18:53 UTC, naseemkullah commented on index.js
> +  const { repoSource } = build.source || null;
The idea behind this change is to safeguard for github app triggered builds that indeed do contain `build.source` in their build object, but they do not contain `build.source.repoSource` from what I've seen. Could you confirm that github triggered apps do not contain `build.source.repoSource` ? The one that I have checked only has`build.source.storageSource`... but no `build.source.repoSource`.

Provided that is indeed true (it is from the github app triggered build I inspected):
If we only check for `build.source` the if condition evaluates to true and tries to fetch `build.source.repoSource.repoName` and `build.source.repoSource.branchName` which don't exist for github app triggered builds (once again from what I've seen)

2019-06-01 18:54 UTC, naseemkullah commented on test.js
> +    // const build = lib.eventToBuild(base64Build);
Yes.

2019-06-03 15:48 UTC, naseemkullah commented on index.js
> +  const { repoSource } = build.source || null;
I spoke to a cloud build engineer and it seems that github app triggered builds indeed do not, and *most likely* will not contain `build.source.repoSource` properties. So I think it's safe to move forward with this..

2019-06-05 23:59 UTC, Philmod approved these changes

2019-06-06 00:00 UTC, merged